Algoritmo "número N digitado pelo usuário"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professora   :  Helida Batista
// Descrição   : Leia um número N digitado pelo usuário e imprima de 1 até N, de dois em dois. Estrutura: PARA.
// Autor(a)    : Joadson Rocha 
// Data atual  : 06/08/2026
Var
// Seção de Declarações das variáveis nome
numero, i: inteiro 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  
  para i de 1 ate 20 passo 2 faca
    escreval(i)
  fimpara

Fimalgoritmo