Algoritmo "Solicite ao usuário um número inteiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professora   :  Helida Batista
// Descrição   : Solicite ao usuário um número inteiro, repita a leitura até que seja informado um número maior que zero. Depois exiba o número digitado. Estrutura: REPITA.
// Autor(a)    : Joadson Rocha 
// Data atual  : 06/08/2026
Var
// Seção de Declarações das variáveis nome
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    
    repita
        escreval("Digite um número inteiro: ")
        leia(numero)
    ATÉ numero > 0
    Escreval("Número digitado: ", numero)
 
 
Fimalgoritmo
   
 

