Algoritmo "DIA DA SEMANA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professora   :  Helida Batista
// Descrição   :   Dia da semamana casos
// Autor(a)    : Joadson Rocha 
// Data atual  : 05/08/2026
Var
// Seção de Declarações das variáveis nome
dia: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Escolha um dia da semana de 1 a 7")
   leia(dia)
   escolha dia
    caso 1
      escreval("Domingo")
      caso 2
      escreval("Segunda-feira")
      caso  3
      escreval("Terça-feira")
        caso 4
        escreval("Quarta-feira")
        caso 5
        escreval("Quinta-feira")
        caso 6
        escreval("Sexta-feira")     
    caso 7
      escreval("Sábado")
    outrocaso
        escreval("Dia inválido")
        fimescolha


   

Fimalgoritmo