Algoritmo "opções de conversão"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professora   :  Helida Batista
// Descrição   : Mostre as opções de conversão, leia a opção desejada e faça a conversão do número inserido: 1 – Metros → Centímetros; 2 – Quilos → Gramas; 3 – Horas → Minutos; 4 – Dias → Horas.
// Autor(a)    : Joadson Rocha 
// Data atual  : 05/08/2026
Var
// Seção de Declarações das variáveis nome
metros, quilos, horas, dias, esc: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval("1 – Metros → Centímetros; 2 – Quilos → Gramas; 3 – Horas → Minutos; 4 – Dias → Horas ")
   
    
    
    


Fimalgoritmo