Algoritmo " produto da compra de um cliente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professora   :  Helida Batista
// Descrição   : Leia o valor de cada produto da compra de um cliente. A leitura deve continuar enquanto o valor informado for diferente de 0. Ao final, exiba o valor total das compras. Estrutura: ENQUANTO.
// Autor(a)    : Joadson Rocha 
// Data atual  : 06/08/2026
Var
// Seção de Declarações das variáveis nome

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    
   
 
 

Fimalgoritmo