Algoritmo "Exiba o menu"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professora   :  Helida Batista
// Descrição   : Exiba o menu: 1 – Novo cadastro, 2 – Consultar, 3 – Sair. Leia a opção escolhida até que o usuário escolha uma opção válida (1, 2 ou 3), depois informe qual opção foi escolhida. Estrutura: REPITA.
// Autor(a)    : Joadson Rocha 
// Data atual  : 06/08/2026
Var
// Seção de Declarações das variáveis nome
opcao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    
    repita
        escreval("Digite uma opção ")
        leia(opcao)
        Escreval("1 – Novo cadastro")
        Escreval("2 – Consultar")
        Escreval("3 – Sair")
       
    ATÉ opcao >= 1 e opcao <= 3
    Escreval("Opção escolhida: ", opcao)
 
Fimalgoritmo
   
 

